main: eu.ialbhost.compactor.Main
name: Compactor
version: 2.0
author: [raks321, mikroskeem]
description: Compact your items
commands:
  compact:
    description: Compact all possible items in your inventory
    usage: /compact or /compactor
    aliases: [compactor]
    permission: compactor.use
    permission-message: You don't have the compact.use permission.